(ru) fix added missing id to div
Некоторые примеры показывали следующую ошибку: 
Error details:
KumascriptError: unable to find an HTML element with an "id" of "Two_Dimensional_With_Grid" within /ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

Поправил добавление id элемента.